### ISSUE TITLE
Support for TLDs .dj, .gr, .np, .pa, and .vn

### ISSUE THREAD

**Issue by jonathansampson** [LayeredStudio/whoiser#89]
**Version(s) affected**: 1.14.0

**Description**  

```
Error: TLD <domain with one of the aforementioned TLDs> not found
    at whoisTld (whoiser.js:118:9)
    at async whoisDomain (whoiser.js:137:15)
```

**Comment by AndreiIgna** [comment]
this is not kinda fixed by #86

To query WHOIS for a domain, the library needs to know the WHOIS server for that TLD. It finds it in this order:
1) cached/hard-coded whois server https://github.com/LayeredStudio/whoiser/blob/master/src/whoiser.js#L9
2) query whois.iana.org for TLD info
3) when no `tld.whois` is found, query alternate TLD sources #80 

The error was returned because `tld.whois` was empty. Now the library doesn't throw an error, but it returns the TLD info without `whois`. Example for `.vn`:
<img width="405" alt="Screenshot 2023-02-04 at 12 38 59" src="https://user-images.githubusercontent.com/263021/216762502-a3473c6d-2710-48d7-b5e6-6511d43e3340.png">

For cases like these, the TLD whois server needs to be found and added in the `whoiser.js -> cacheTldWhoisServer variable`
